from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from sqlalchemy import text
from typing import List
from decimal import Decimal
from pydantic import BaseModel
from app.core.database import get_db

router = APIRouter(prefix="/analytics", tags=["analytics"])

# Analytics Response Schemas
class TopFilmResponse(BaseModel):
    film_id: int
    title: str
    rental_count: int

class FilmRevenueResponse(BaseModel):
    film_id: int
    title: str
    total_revenue: Decimal

class CategoryRevenueResponse(BaseModel):
    category_id: int
    name: str
    total_revenue: Decimal

class CustomerActivityResponse(BaseModel):
    rental_month: str
    total_rentals: int

class StoreAvailabilityResponse(BaseModel):
    store_id: int
    total_items: int
    rented_items: int
    available_items: int


@router.get("/top-films", response_model=List[TopFilmResponse])
def get_top_films(db: Session = Depends(get_db)):
    """
    Get the top 10 most rented films.
    """
    query = text("""
        SELECT 
            f.film_id,
            f.title,
            COUNT(r.rental_id) AS rental_count
        FROM film f
        JOIN inventory i ON f.film_id = i.film_id
        JOIN rental r ON i.inventory_id = r.inventory_id
        GROUP BY f.film_id, f.title
        ORDER BY rental_count DESC
        LIMIT 10;
    """)
    result = db.execute(query).mappings().all()
    return result


@router.get("/revenue-by-film", response_model=List[FilmRevenueResponse])
def get_revenue_by_film(db: Session = Depends(get_db)):
    """
    Get total revenue generated by each film.
    """
    query = text("""
        SELECT 
            f.film_id,
            f.title,
            COALESCE(SUM(p.amount), 0.0) AS total_revenue
        FROM film f
        JOIN inventory i ON f.film_id = i.film_id
        JOIN rental r ON i.inventory_id = r.inventory_id
        JOIN payment p ON r.rental_id = p.rental_id
        GROUP BY f.film_id, f.title
        ORDER BY total_revenue DESC;
    """)
    result = db.execute(query).mappings().all()
    return result


@router.get("/revenue-by-category", response_model=List[CategoryRevenueResponse])
def get_revenue_by_category(db: Session = Depends(get_db)):
    """
    Get total revenue generated by film category.
    """
    query = text("""
        SELECT 
            c.category_id,
            c.name,
            COALESCE(SUM(p.amount), 0.0) AS total_revenue
        FROM category c
        JOIN film_category fc ON c.category_id = fc.category_id
        JOIN film f ON fc.film_id = f.film_id
        JOIN inventory i ON f.film_id = i.film_id
        JOIN rental r ON i.inventory_id = r.inventory_id
        JOIN payment p ON r.rental_id = p.rental_id
        GROUP BY c.category_id, c.name
        ORDER BY total_revenue DESC;
    """)
    result = db.execute(query).mappings().all()
    return result


@router.get("/customer-activity", response_model=List[CustomerActivityResponse])
def get_customer_activity(db: Session = Depends(get_db)):
    """
    Get total monthly rental activity volume.
    """
    query = text("""
        SELECT 
            DATE_FORMAT(rental_date, '%Y-%m') AS rental_month,
            COUNT(rental_id) AS total_rentals
        FROM rental
        GROUP BY rental_month
        ORDER BY rental_month ASC;
    """)
    result = db.execute(query).mappings().all()
    return result


@router.get("/inventory-availability", response_model=List[StoreAvailabilityResponse])
def get_inventory_availability(db: Session = Depends(get_db)):
    """
    Get the inventory count and item availability for each store.
    """
    query = text("""
        SELECT 
            i.store_id,
            COUNT(DISTINCT i.inventory_id) AS total_items,
            COALESCE(SUM(CASE WHEN r.rental_id IS NOT NULL AND r.return_date IS NULL THEN 1 ELSE 0 END), 0) AS rented_items,
            COALESCE(SUM(CASE WHEN r.rental_id IS NULL OR r.return_date IS NOT NULL THEN 1 ELSE 0 END), 0) AS available_items
        FROM inventory i
        LEFT JOIN rental r ON i.inventory_id = r.inventory_id
        AND r.rental_date = (
            SELECT MAX(r2.rental_date)
            FROM rental r2
            WHERE r2.inventory_id = i.inventory_id
        )
        GROUP BY i.store_id;
    """)
    result = db.execute(query).mappings().all()
    return result
